version: '3.7'

services:

    db:
        env_file: ./prisma/.env
        image: postgres
        restart: 'no'
                    
        ports: 
            - "5432:5432"

    adminer:
        image: adminer
        restart: 'no'
        ports:
            - 8080:8080